// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Retaguarda.Persistencia;

#nullable disable

namespace Retaguarda.Persistencia.MYSQL
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Funcao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<long>("OrganizacaoId")
                        .HasColumnType("bigint");
                    b.Property<long?>("OrganizacaoSetorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizacaoId");

                    b.ToTable("Funcoes", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Organizacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Organizacoes", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.OrganizacaoSetor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<long>("OrganizacaoId")
                        .HasColumnType("bigint");
                    b.Property<long?>("OrganizacaoSetorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizacaoId");

                    b.ToTable("OrganizacaoSetores", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Perfil", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<long>("OrganizacaoId")
                        .HasColumnType("bigint");
                    b.Property<long?>("OrganizacaoSetorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizacaoId");

                    b.ToTable("Perfis", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.PerfilPermissao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<long>("OrganizacaoId")
                        .HasColumnType("bigint");
                    b.Property<long?>("OrganizacaoSetorId")
                        .HasColumnType("bigint");

                    b.Property<long>("PerfilId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizacaoId");

                    b.HasIndex("PerfilId");

                    b.ToTable("PerfilPermissoes", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<long>("OrganizacaoId")
                        .HasColumnType("bigint");
                    b.Property<long?>("OrganizacaoSetorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizacaoId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Funcao", b =>
                {
                    b.HasOne("Retaguarda.Dominio.Entidades.Organizacao", "Organizacao")
                        .WithMany("Funcoes")
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizacao");
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.OrganizacaoSetor", b =>
                {
                    b.HasOne("Retaguarda.Dominio.Entidades.Organizacao", "Organizacao")
                        .WithMany("Setores")
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizacao");
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Perfil", b =>
                {
                    b.HasOne("Retaguarda.Dominio.Entidades.Organizacao", "Organizacao")
                        .WithMany("Perfis")
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizacao");
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.PerfilPermissao", b =>
                {
                    b.HasOne("Retaguarda.Dominio.Entidades.Organizacao", "Organizacao")
                        .WithMany()
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Retaguarda.Dominio.Entidades.Perfil", "Perfil")
                        .WithMany("Permissoes")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizacao");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Usuario", b =>
                {
                    b.HasOne("Retaguarda.Dominio.Entidades.Organizacao", "Organizacao")
                        .WithMany("Usuarios")
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizacao");
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Organizacao", b =>
                {
                    b.Navigation("Funcoes");

                    b.Navigation("Perfis");

                    b.Navigation("Setores");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Perfil", b =>
                {
                    b.Navigation("Permissoes");
                });
#pragma warning restore 612, 618
        }
    }
}
