// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Retaguarda.Persistencia.MYSQL;

#nullable disable

namespace Retaguarda.Persistencia.MYSQL
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Bairro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("MunicipioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UltimoAcessoOrganizacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UltimoAcessoOrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UltimoAcessoSetorId")
                        .HasColumnType("bigint");

                    

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MunicipioId");

                    b.ToTable("Bairros", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Cep", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("ImovelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ImovelId");

                    b.ToTable("Ceps", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Endereco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("CepId")
                        .HasColumnType("bigint");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CepId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Enderecos", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Funcao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizacaoId");

                    b.ToTable("Funcoes", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Imovel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Cadastro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("LogradouroId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LogradouroId");

                    b.ToTable("Imoveis", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Logradouro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("BairroId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BairroId");

                    b.ToTable("Logradouros", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Municipio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<long>("UfId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UfId");

                    b.ToTable("Municipios", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Organizacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Organizacoes", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.OrganizacaoSetor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizacaoId");

                    b.ToTable("OrganizacaoSetores", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.OrganizacaoUnidade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizacaoId");

                    b.ToTable("OrganizacaoUnidades", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.OrganizacaoUnidadeSetor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizacaoUnidadeId");

                    b.ToTable("OrganizacaoUnidadeSetores", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Pais", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Paises", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Perfil", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("AdministradorDoSistema")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizacaoId");

                    b.ToTable("Perfis", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.PerfilPermissao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long>("PerfilId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizacaoId");

                    b.HasIndex("PerfilId");

                    b.ToTable("PerfilPermissoes", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.PerfilUsuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long>("PerfilId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PerfilUsuarios", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.SetorUsuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("HabilitarPermissoesNegativas")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SetorId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SetorUsuarios", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Uf", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long>("PaisId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.ToTable("Ufs", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("OrganizacaoId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Bairro", b =>
                {
                    b.HasOne("Retaguarda.Dominio.Entidades.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Cep", b =>
                {
                    b.HasOne("Retaguarda.Dominio.Entidades.Imovel", "Imovel")
                        .WithMany()
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Imovel");
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Endereco", b =>
                {
                    b.HasOne("Retaguarda.Dominio.Entidades.Cep", "Cep")
                        .WithMany()
                        .HasForeignKey("CepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Retaguarda.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cep");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Funcao", b =>
                {
                    b.HasOne("Retaguarda.Dominio.Entidades.Organizacao", "Organizacao")
                        .WithMany("Funcoes")
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Organizacao");
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Imovel", b =>
                {
                    b.HasOne("Retaguarda.Dominio.Entidades.Logradouro", "Logradouro")
                        .WithMany()
                        .HasForeignKey("LogradouroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logradouro");
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Logradouro", b =>
                {
                    b.HasOne("Retaguarda.Dominio.Entidades.Bairro", "Bairro")
                        .WithMany()
                        .HasForeignKey("BairroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bairro");
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Municipio", b =>
                {
                    b.HasOne("Retaguarda.Dominio.Entidades.Uf", "Uf")
                        .WithMany()
                        .HasForeignKey("UfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uf");
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.OrganizacaoSetor", b =>
                {
                    b.HasOne("Retaguarda.Dominio.Entidades.Organizacao", "Organizacao")
                        .WithMany("Setores")
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Organizacao");
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.OrganizacaoUnidade", b =>
                {
                    b.HasOne("Retaguarda.Dominio.Entidades.Organizacao", "Organizacao")
                        .WithMany()
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Organizacao");
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.OrganizacaoUnidadeSetor", b =>
                {
                    b.HasOne("Retaguarda.Dominio.Entidades.OrganizacaoUnidade", "OrganizacaoUnidade")
                        .WithMany()
                        .HasForeignKey("OrganizacaoUnidadeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("OrganizacaoUnidade");
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Perfil", b =>
                {
                    b.HasOne("Retaguarda.Dominio.Entidades.Organizacao", "Organizacao")
                        .WithMany("Perfis")
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Organizacao");
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.PerfilPermissao", b =>
                {
                    b.HasOne("Retaguarda.Dominio.Entidades.Organizacao", "Organizacao")
                        .WithMany()
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Retaguarda.Dominio.Entidades.Perfil", "Perfil")
                        .WithMany("Permissoes")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizacao");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.PerfilUsuario", b =>
                {
                    b.HasOne("Retaguarda.Dominio.Entidades.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Retaguarda.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.SetorUsuario", b =>
                {
                    b.HasOne("Retaguarda.Dominio.Entidades.OrganizacaoSetor", "Setor")
                        .WithMany()
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Retaguarda.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Setor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Uf", b =>
                {
                    b.HasOne("Retaguarda.Dominio.Entidades.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Usuario", b =>
                {
                    b.HasOne("Retaguarda.Dominio.Entidades.Organizacao", "Organizacao")
                        .WithMany("Usuarios")
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Organizacao");
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Organizacao", b =>
                {
                    b.Navigation("Funcoes");

                    b.Navigation("Perfis");

                    b.Navigation("Setores");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Perfil", b =>
                {
                    b.Navigation("Permissoes");
                });
#pragma warning restore 612, 618
        }
    }
}
