// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Retaguarda.Persistencia.POSTGRESQL;

#nullable disable

namespace Retaguarda.Persistencia.POSTGRESQL.Migracoes
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260825174928_AddModelAssociations")]
    partial class AddModelAssociations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Bairro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdentificadorUnico")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentificadorUnicoAmigavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("MunicipioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioAlteracaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioInsercaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("Versao")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MunicipioId");

                    b.ToTable("Bairros", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Cep", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdentificadorUnico")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentificadorUnicoAmigavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("ImovelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioAlteracaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioInsercaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("Versao")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ImovelId");

                    b.ToTable("Ceps", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Contato", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("ContatoValor")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdentificadorUnico")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentificadorUnicoAmigavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TipoContatoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioAlteracaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioInsercaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("Versao")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Contatos", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.ContatoRelacionamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<long>("ContatoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdentificadorUnico")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentificadorUnicoAmigavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoSetorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PessoaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioAlteracaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioInsercaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("Versao")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ContatoRelacionamentos", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Documento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataEmissao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataValidade")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Digito")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long?>("DocumentoTipoId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("IdentificadorUnico")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentificadorUnicoAmigavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<string>("OrgaoEmissor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Principal")
                        .HasColumnType("boolean");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<string>("UfEmissor")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<long?>("UsuarioAlteracaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioInsercaoId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Validado")
                        .HasColumnType("boolean");

                    b.Property<long>("Versao")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Documentos", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.DocumentoRelacionamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DocumentoId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("IdentificadorUnico")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentificadorUnicoAmigavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoSetorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PessoaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioAlteracaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioInsercaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("Versao")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("DocumentoRelacionamentos", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Endereco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<long?>("BairroId")
                        .HasColumnType("bigint");

                    b.Property<long>("CepId")
                        .HasColumnType("bigint");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdentificadorUnico")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentificadorUnicoAmigavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("LogradouroId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MunicipioId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PaisId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UfId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioAlteracaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioInsercaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("Versao")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CepId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Enderecos", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Imovel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cadastro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("CepId")
                        .HasColumnType("bigint");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdentificadorUnico")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentificadorUnicoAmigavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InscricaoImobiliaria")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<long?>("LogradouroId")
                        .HasColumnType("bigint");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SituacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TipoImovelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioAlteracaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioInsercaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("Versao")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CepId");

                    b.HasIndex("LogradouroId");

                    b.ToTable("Imoveis", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Logradouro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<long>("BairroId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdentificadorUnico")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentificadorUnicoAmigavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("UsuarioAlteracaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioInsercaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("Versao")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BairroId");

                    b.ToTable("Logradouros", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Municipio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<long?>("CepId")
                        .HasColumnType("bigint");

                    b.Property<string>("CodigoIbge")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdentificadorUnico")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentificadorUnicoAmigavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<long>("UfId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioAlteracaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioInsercaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("Versao")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UfId");

                    b.ToTable("Municipios", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.NaturezaJuridica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdentificadorUnico")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentificadorUnicoAmigavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioAlteracaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioInsercaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("Versao")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("NaturezasJuridicas", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.NivelGoverno", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdentificadorUnico")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentificadorUnicoAmigavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioAlteracaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioInsercaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("Versao")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("NiveisGoverno", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Organizacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HierarquiaCodigo")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<Guid>("IdentificadorUnico")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentificadorUnicoAmigavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoPaiId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoRaizId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ResponsavelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<long?>("SituacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioAlteracaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioInsercaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("Versao")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Organizacoes", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.OrganizacaoEndereco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EnderecoId")
                        .HasColumnType("bigint");

                    b.Property<bool>("EnderecoPrincipal")
                        .HasColumnType("boolean");

                    b.Property<long?>("EnderecoTipoId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("IdentificadorUnico")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentificadorUnicoAmigavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OrganizacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioAlteracaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioInsercaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("Versao")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("OrganizacaoEnderecos", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.OrganizacaoSetor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("CodigoHierarquico")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdentificadorUnico")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentificadorUnicoAmigavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ResponsavelSetorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioAlteracaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioInsercaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("Versao")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("OrganizacaoSetores", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.OrganizacaoSetorEndereco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EnderecoId")
                        .HasColumnType("bigint");

                    b.Property<bool>("EnderecoPrincipal")
                        .HasColumnType("boolean");

                    b.Property<long?>("EnderecoTipoId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("IdentificadorUnico")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentificadorUnicoAmigavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrganizacaoSetorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioAlteracaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioInsercaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("Versao")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("OrganizacaoSetorEnderecos", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.OrganizacaoUnidade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HierarquiaCodigo")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<string>("HierarquiaNome")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("IdentificadorUnico")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentificadorUnicoAmigavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("Nivel")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<long?>("UnidadePaiId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioAlteracaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioInsercaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("Versao")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("OrganizacaoUnidades", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.OrganizacaoUnidadeEndereco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EnderecoId")
                        .HasColumnType("bigint");

                    b.Property<bool>("EnderecoPrincipal")
                        .HasColumnType("boolean");

                    b.Property<long?>("EnderecoTipoId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("IdentificadorUnico")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentificadorUnicoAmigavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioAlteracaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioInsercaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("Versao")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("OrganizacaoUnidadeEnderecos", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.OrganizacaoUnidadeSetor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdentificadorUnico")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentificadorUnicoAmigavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioAlteracaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioInsercaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("Versao")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizacaoUnidadeId");

                    b.ToTable("OrganizacaoUnidadeSetores", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.OrquestracaoFluxoProcesso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("IdentificadorUnico")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentificadorUnicoAmigavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioAlteracaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioInsercaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("Versao")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkflowDefinitionId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("WorkflowJson")
                        .HasColumnType("text");

                    b.Property<string>("WorkflowNome")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("WorkflowVersion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("OrquestracaoFluxoProcessos", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Pais", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdentificadorUnico")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentificadorUnicoAmigavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioAlteracaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioInsercaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("Versao")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Paises", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Perfil", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AdministradorDoSistema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdentificadorUnico")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentificadorUnicoAmigavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioAlteracaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioInsercaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("Versao")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Perfis", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.PerfilPermissao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdentificadorUnico")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentificadorUnicoAmigavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long>("PerfilId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioAlteracaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioInsercaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("Versao")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId", "Chave")
                        .IsUnique();

                    b.ToTable("PerfilPermissoes", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.PerfilUsuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdentificadorUnico")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentificadorUnicoAmigavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long>("PerfilId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioAlteracaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioInsercaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("Versao")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PerfilUsuarios", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Pessoa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Discriminator")
                        .HasColumnType("integer");

                    b.Property<Guid>("IdentificadorUnico")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentificadorUnicoAmigavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<int>("TipoPessoa")
                        .HasColumnType("integer");

                    b.Property<long?>("UsuarioAlteracaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioInsercaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("Versao")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Pessoas", (string)null);

                    b.HasDiscriminator().HasValue(0);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.PessoaEndereco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EnderecoId")
                        .HasColumnType("bigint");

                    b.Property<bool>("EnderecoPrincipal")
                        .HasColumnType("boolean");

                    b.Property<long?>("EnderecoTipoId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("IdentificadorUnico")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentificadorUnicoAmigavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long>("PessoaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioAlteracaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioInsercaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("Versao")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("PessoaEnderecos", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.SetorUsuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HabilitarPermissoesNegativas")
                        .HasColumnType("boolean");

                    b.Property<Guid>("IdentificadorUnico")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentificadorUnicoAmigavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Padrao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<long>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioAlteracaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioInsercaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("Versao")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SetorId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SetorUsuarios", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Situacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Contexto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("IdentificadorUnico")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentificadorUnicoAmigavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioAlteracaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioInsercaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("Versao")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Codigo", "Contexto", "OrganizacaoId")
                        .IsUnique()
                        .HasDatabaseName("idx_Situacoes_Codigo_Contexto_Unico");

                    b.HasIndex("OrganizacaoId", "Contexto", "Ativo")
                        .HasDatabaseName("idx_Situacoes_Contexto_Ativo");

                    b.ToTable("Situacoes", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Tipo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Contexto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("IdentificadorUnico")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentificadorUnicoAmigavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("Ordem")
                        .HasColumnType("integer");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioAlteracaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioInsercaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("Versao")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Codigo", "Contexto", "OrganizacaoId")
                        .IsUnique()
                        .HasDatabaseName("idx_Tipos_Codigo_Contexto_Unico");

                    b.HasIndex("OrganizacaoId", "Contexto", "Ativo")
                        .HasDatabaseName("idx_Tipos_Contexto_Ativo");

                    b.ToTable("Tipos", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Uf", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdentificadorUnico")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentificadorUnicoAmigavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long>("PaisId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<long?>("UsuarioAlteracaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioInsercaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("Versao")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.ToTable("Ufs", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("IdentificadorUnico")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentificadorUnicoAmigavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PessoaId")
                        .HasColumnType("bigint");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UltimoAcessoOrganizacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UltimoAcessoOrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UltimoAcessoSetorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioAlteracaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioInsercaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("Versao")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.UsuarioEndereco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EnderecoId")
                        .HasColumnType("bigint");

                    b.Property<bool>("EnderecoPrincipal")
                        .HasColumnType("boolean");

                    b.Property<long?>("EnderecoTipoId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("IdentificadorUnico")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentificadorUnicoAmigavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("OrganizacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizacaoUnidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioAlteracaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioInsercaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("Versao")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("UsuarioEnderecos", (string)null);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.PessoaFisica", b =>
                {
                    b.HasBaseType("Retaguarda.Dominio.Entidades.Pessoa");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataObito")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EstadoCivil")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("NomeMae")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("NomePai")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("NomeSocial")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("Pcd")
                        .HasColumnType("boolean");

                    b.Property<int?>("Sexo")
                        .HasColumnType("integer");

                    b.ToTable("Pessoas", (string)null);

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.PessoaJuridica", b =>
                {
                    b.HasBaseType("Retaguarda.Dominio.Entidades.Pessoa");

                    b.Property<string>("Anotacoes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<DateTime?>("DataExtincao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataFundacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InscricaoEstadual")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("InscricaoMunicipal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<long?>("SituacaoId")
                        .HasColumnType("bigint");

                    b.ToTable("Pessoas", (string)null);

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Bairro", b =>
                {
                    b.HasOne("Retaguarda.Dominio.Entidades.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Cep", b =>
                {
                    b.HasOne("Retaguarda.Dominio.Entidades.Imovel", "Imovel")
                        .WithMany()
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Imovel");
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Endereco", b =>
                {
                    b.HasOne("Retaguarda.Dominio.Entidades.Cep", "Cep")
                        .WithMany()
                        .HasForeignKey("CepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Retaguarda.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cep");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Imovel", b =>
                {
                    b.HasOne("Retaguarda.Dominio.Entidades.Cep", "Cep")
                        .WithMany()
                        .HasForeignKey("CepId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Retaguarda.Dominio.Entidades.Logradouro", "Logradouro")
                        .WithMany()
                        .HasForeignKey("LogradouroId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cep");

                    b.Navigation("Logradouro");
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Logradouro", b =>
                {
                    b.HasOne("Retaguarda.Dominio.Entidades.Bairro", "Bairro")
                        .WithMany()
                        .HasForeignKey("BairroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bairro");
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Municipio", b =>
                {
                    b.HasOne("Retaguarda.Dominio.Entidades.Uf", "Uf")
                        .WithMany()
                        .HasForeignKey("UfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uf");
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.OrganizacaoUnidadeSetor", b =>
                {
                    b.HasOne("Retaguarda.Dominio.Entidades.OrganizacaoUnidade", "OrganizacaoUnidade")
                        .WithMany()
                        .HasForeignKey("OrganizacaoUnidadeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("OrganizacaoUnidade");
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.PerfilPermissao", b =>
                {
                    b.HasOne("Retaguarda.Dominio.Entidades.Perfil", "Perfil")
                        .WithMany("Permissoes")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.PerfilUsuario", b =>
                {
                    b.HasOne("Retaguarda.Dominio.Entidades.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Retaguarda.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.SetorUsuario", b =>
                {
                    b.HasOne("Retaguarda.Dominio.Entidades.OrganizacaoSetor", "Setor")
                        .WithMany()
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Retaguarda.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Setor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Uf", b =>
                {
                    b.HasOne("Retaguarda.Dominio.Entidades.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Retaguarda.Dominio.Entidades.Perfil", b =>
                {
                    b.Navigation("Permissoes");
                });
#pragma warning restore 612, 618
        }
    }
}
