// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Retaguarda.Persistencia.MYSQL;

#nullable disable

namespace Retaguarda.Persistencia.MYSQL.Migracoes
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260804200632_AddMunicipioCodigoIbge")]
    partial class AddMunicipioCodigoIbge
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");
        }
    }
}